modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
issueTrackerURL="https://github.com/StrandedOnPlanetPixel/BlocksPlusPlus/issues" #optional
[[mods]] #mandatory
modId="blocksplusplus" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Blocks++" #mandatory
displayURL="https://github.com/StrandedOnPlanetPixel/BlocksPlusPlus" #optional
logoFile="src/resources/assets/blocksplusplus/textures/logo.png"
authors="Amanda Aldrich, Zira Cook, Taylor Riccetti" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Blocks++, it adds blocks and more blocks
'''